spring:
    application:
        name: siach-api
    flyway:
        enabled: true
    security:
        ignored: "*.bundle.*"
        user:
            name: test
            password: test
    main:
        allow-circular-references: true
        allow-bean-definition-overriding: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
    datasource:
        driverClassName: ${DATABASE_DRIVER:org.postgresql.Driver}
