spring:
    application:
        name: siach-api
    flyway:
        enabled: true
    security:
        ignored: "*.bundle.*"
        user:
            name: test
            password: test
    main:
        allow-circular-references: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    datasource:
        driverClassName: ${DATABASE_DRIVER:oracle.jdbc.OracleDriver}
        url: ${DATABASE_URL:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=DESKTOP-K8VVECH)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=XE)))}
        username: ${DATABASE_USERNAME:c##scott}
        password: ${DATABASE_PASSWORD:tiger}
